name: etlegacy
summary: FPS Game
version: 2.83.2
description: |
  Welcome to ET: Legacy, an open source project that aims to create a fully compatible client
  and server for the popular online FPS game Wolfenstein: Enemy Territory - whose gameplay
  is still considered unmatched by many, despite its great age.
base: core24
adopt-info: etl
compression: lzo
confinement: strict
source-code: https://github.com/etlegacy/etlegacy-snap
website: https://www.etlegacy.com
contact: https://discord.gg/UBAZFys
issues: https://github.com/etlegacy/etlegacy/issues/
license: GPL-3.0

parts:
  etl:
    plugin: nil
    stage-packages:
      - wget
      - curl
      - libgl1
  wrappers:
    plugin: dump
    source: ./wrappers
    organize:
      etl: bin/etl
      etlded: bin/etlded
    prime:
      - bin/etl
      - bin/etlded

apps:
  etl:
    extensions: [gnome]
    command: bin/etl
    plugs:
      - opengl
      - x11
      - wayland
      - audio-playback
      - joystick
      - network
      - hardware-observe

  etlded:
    command: bin/etlded
    plugs:
      - network
      - network-bind
      - hardware-observe

