#!/bin/sh
set -e
pack_downloader() {
if [ -f /usr/bin/curl ]; then
curl -P ${SNAP_USER_DATA}/etlegacy*/etmain $1
else
wget -P ${SNAP_USER_DATA}/etlegacy*/etmain $1
fi
}
if [ ! -d ${SNAP_USER_DATA}/etlegacy* ]; then
case "$SNAP_ARCH" in
    amd64) wget `curl https://www.etlegacy.com/download | grep "x86_64 archive" | grep -Eoi '<a [^>]+>' | grep -Eo 'href=\"[^\\\"]+\"' | grep -Eo '(http|https):\/\/[^\"]+'` -O ${SNAP_USER_DATA}/etl.tar.gz
    cd "$SNAP_USER_DATA" || exit 1
    tar -xvzf ${SNAP_USER_DATA}/etl.tar.gz
    rm -rf ${SNAP_USER_DATA}/etl.tar.gz ;;
    i386) wget `curl https://www.etlegacy.com/download | grep "i386 archive" | grep -Eoi '<a [^>]+>' | grep -Eo 'href=\"[^\\\"]+\"' | grep -Eo '(http|https):\/\/[^\"]+'` -O ${SNAP_USER_DATA}/etl.tar.gz
    cd "$SNAP_USER_DATA" || exit 1
    tar -xvzf ${SNAP_USER_DATA}/etl.tar.gz
    rm -rf ${SNAP_USER_DATA}/etl.tar.gz ;;
    arm64) wget `curl https://www.etlegacy.com/download | grep "AArch64 archive" | grep -Eoi '<a [^>]+>' | grep -Eo 'href=\"[^\\\"]+\"' | grep -Eo '(http|https):\/\/[^\"]+'` -O ${SNAP_USER_DATA}/etl.tar.gz
    cd "$SNAP_USER_DATA" || exit 1
    tar -xvzf ${SNAP_USER_DATA}/etl.tar.gz
    rm -rf ${SNAP_USER_DATA}/etl.tar.gz ;;
    *) echo "Unsupported arch: $SNAP_ARCH"; exit 1 ;;
esac
fi
for dir in */ ;
do
if [ ! -d ${SNAP_USER_DATA}/.etlded ]; then
    mkdir ${SNAP_USER_DATA}/.etlded
   
    if [ ! -d ${SNAP_USER_DATA}/.etlded/etmain ]; then
mkdir ${SNAP_USER_DATA}/.etlded/etmain
    fi
   
    if [ ! -d ${SNAP_USER_DATA}/.etlded/legacy ]; then
mkdir ${SNAP_USER_DATA}/.etlded/legacy
    fi
fi
    if [ ! -f ${SNAP_USER_DATA}/etlegacy*/etmain/pak0.pk3 ]; then
pack_downloader https://mirror.etlegacy.com/etmain/pak0.pk3
    fi
    if [ ! -f ${SNAP_USER_DATA}/etlegacy*/etmain/pak1.pk3 ]; then
pack_downloader https://mirror.etlegacy.com/etmain/pak1.pk3
    fi
    if [ ! -f ${SNAP_USER_DATA}/etlegacy*/etmain/pak2.pk3 ]; then
pack_downloader https://mirror.etlegacy.com/etmain/pak2.pk3
    fi

done
case "$SNAP_ARCH" in
    amd64) ${SNAP_USER_DATA}/etlegacy*/etlded.x86_64 +set fs_basepath ${SNAP_USER_DATA}/etlegacy* +set fs_homepath ${SNAP_USER_DATA}/.etlded +set g_protect 1 +set omnibot_enable 1 +set omnibot_path "${SNAP_USER_DATA}/.etlded/legacy/omni-bot" +exec etl_server.cfg ;;
    i386) ${SNAP_USER_DATA}/etlegacy*/etlded.i386 +set fs_basepath ${SNAP_USER_DATA}/etlegacy* +set fs_homepath ${SNAP_USER_DATA}/.etlded +set g_protect 1 +set omnibot_enable 1 +set omnibot_path "${SNAP_USER_DATA}/.etlded/legacy/omni-bot" +exec etl_server.cfg ;;
    arm64) ${SNAP_USER_DATA}/etlegacy*/etlded.aarch64 +set fs_basepath ${SNAP_USER_DATA}/etlegacy* +set fs_homepath ${SNAP_USER_DATA}/.etlded +set g_protect 1 +set omnibot_enable 1 +set omnibot_path "${SNAP_USER_DATA}/.etlded/legacy/omni-bot" +exec etl_server.cfg ;;
    *)       echo "Unsupported arch: $SNAP_ARCH"; exit 1 ;;
esac
